config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new', as: :login
  get '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :issues do
    resources :options do
      resources :pros_doings
      resources :cons_doings
      resources :pros_not_doings
      resources :cons_not_doings
    end
  end
  resources :users
  resources :comments

  mount ActionCable.server => '/cable'   #obvious requirement for AC
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user
  validates :provider, :uid, :presence => true

  def self.find_or_create(auth_hash)
    unless auth = find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
      user = User.create(name: auth_hash["info"]["name"], email: auth_hash["info"]["email"])
      auth = create(user: user, provider: auth_hash["provider"], uid: auth_hash["uid"])
    end
    auth
  end

  def self.find_by_provider_and_uid(provider, uid)
    Authorization.find_by(provider: provider, uid: uid)
  end

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
end

app/models/cons_doing.rb
class ConsDoing < ApplicationRecord
  belongs_to :option
end

app/models/cons_not_doing.rb
class ConsNotDoing < ApplicationRecord
  belongs_to :option
end

app/models/issue.rb
class Issue < ApplicationRecord
  has_many :pros_doings, through: :options
  has_many :cons_doings, through: :options
  has_many :pros_not_doings, through: :options
  has_many :cons_not_doings, through: :options
  accepts_nested_attributes_for :options
  validates :name, presence: true

  belongs_to :user
  has_many :options

  def self.open_issues
    open_issues = Issue.where("open = ?", true)
    public_issues = Issue.where("private = ?", false)
  end
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :issue
  has_many :pros_doings
  has_many :cons_doings
  has_many :pros_not_doings
  has_many :cons_not_doings

end

app/models/pros_doing.rb
class ProsDoing < ApplicationRecord
  belongs_to :option
end

app/models/pros_not_doing.rb
class ProsNotDoing < ApplicationRecord
  belongs_to :option
end

app/models/user.rb
class User < ApplicationRecord
  has_many :issues
  has_many :comments
  has_many :authorizations
  validates :name, :email, :presence => true

  def add_provider(auth_hash)
    unless authorizations.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"])
      Authorization.create :user => self, :provider => auth_hash["provider"], :uid => auth_hash["uid"]
    end
  end



end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :select_issue, only: [:show, :edit, :update, :destroy]

  def index
    @issues = Issue.open_issues && Issue.public_issues
  end

  def new
    @issue = Issue.new
    3.times do
      @issue.options << Option.new
    end
  end

  def create
    @issue = Issue.new(issue_params)
    @issue.user_id = 1 #current_user
    @issue.save
    redirect_to issues_path(@issue)
  end

  def show
    @options = @issue.options
  end

  def update
    while @issues.options < 4
      @issue.options << Option.new
    end
    @issue.update(issue_params)
    @issue.save
    redirect_to issue_path(@issue)
  end

  def destroy
    @issue.destroy
    redirect_to issues_path
  end

  private

  def issue_params
    params.require(:issue).permit(:name, :open, :private, options: [:id, :name])
  end

  def select_issue
    @issue = Issue.find(params[:id])
  end

end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :select_options, only: [:show]

  def show
  end

  private

  def select_options
    @options = options.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


  def new
  end

  def create
    auth_hash = request.env["omniauth.auth"]
    if session[:user_id]
      User.find(session[:user_id]).add_provider(auth_hash)
    else
      auth = Authorization.find_or_create(auth_hash)
      session[:user_id] = auth.user.id
    end
  end



#
  def failure
    # render :text => "Sorry but you didn't allow access to our app!"
  end
#
#
  def destroy
    session[:user_id] = nil
    # render :text => "You've logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cons_doing_helper.rb
module ConsDoingHelper
end

app/helpers/cons_not_doing_helper.rb
module ConsNotDoingHelper
end

app/helpers/issues_helper.rb
module IssuesHelper

  def create_options(issue)
    3.times do
      issue.options << Option.new
    end
  end

end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/pros_doing_helper.rb
module ProsDoingHelper
end

app/helpers/pros_not_doing_helper.rb
module ProsNotDoingHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/issues/_new_form.html.erb
<%= form_for @issue do |f| %>
    <%= f.label :name, "Issue Name" %> <br>
    <%= f.text_field :name %> <br> <br>
  </div>
  <div>
    <%= f.fields_for :options do |option| %>
      <%= option.label :name, "Option #{option.index + 1}" %> <br>
      <%= option.text_field :name, value: "", placeholder: "Enter an Option" %> <br> <br>
    <% end %>
    <%= f.label :quad, "Quad view?" %>
    <%= f.check_box :quad %> <br>
    <%= f.label :dual, "Dual view?" %>
    <%= f.check_box :dual %> <br>
    <%= f.label :private, "Make issue private? :" %>
    <%= f.check_box :private %> <br><br>
  </div>
  <br>
  <%= f.submit %>
<% end %>

app/views/issues/edit.html.erb
<%= render 'new_form' %>

app/views/issues/index.html.erb
<h1>Open Public Issues</h1>
<% @issues.each do |issue| %>
  <%= link_to issue.name, issue_path(issue) %> <br>
<% end %>
<br>

<%= link_to "New Issue", new_issue_path %>

app/views/issues/new.html.erb
THIS IS THE ISSUES NEW PAGE

app/views/issues/show.html.erb
<h1> <%= @issue.name %> </h1> <br>
<ul>
  <% @issue.options.each do |opt| %>
    <li><h3><%= opt.name %></li></h3> <br>
    Pros of Doing This Option
    <ul>
      <% opt.pros_doings.each do |pro| %>
        <li><%= pro.description %></li> <br>
      <% end %>
    </ul>
    Cons of Doing this Option
    <ul>
      <% opt.cons_doings.each do |con| %>
        <li><%= con.description %></li> <br>
    </ul>
    <% end %>
    <% if @issue.quad == true %>
      Pros of Not Doing this Option
        <ul>
          <% opt.pros_not_doings.each do |pro| %>
            <li><%= pro.description %></li> <br>
        </ul>
      <% end %>
      Cons of Not Doing this Option
      <ul>
        <% opt.cons_not_doings.each do |con| %>
          <li><%= con.description %></li>
      </ul>
      <% end %>
    <% end %>
  <% end %>
</ul>

<%= link_to "Edit Issue", edit_issue_path %>
<%= link_to "Delete Issue", issue_path, method: :delete %>

app/views/users/index.html.erb
THIS IS THE USERS INDEX PAGE

app/views/users/show.html.erb
THIS IS THE USERS SHOW PAGE